version: "3"

services:
  registration_app:
    build: ./build
    container_name: registration_app
    restart: always
    tty: true
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
    command: bash /entrypoint.sh
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ../:/app
    networks:
      - application
      - registration_db
      - registration_app

  registration_db:
    image: postgres:15-alpine
    container_name: registration_db
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432
    volumes:
      - /tmp/registration_db:/var/lib/postgresql/data
    networks:
      - registration_db

networks:
  registration_db:
    driver: bridge
  registration_app:
    driver: bridge
  application:
    external: true
