version: "3"

services:
  cache:
    image: redis:7.0.7-alpine
    container_name: cache
    restart: always
    tty: true
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ../:/app
    networks:
      - registration_app

networks:
  registration_app:
    driver: bridge
