version: "3"

services:
  cache:
    image: redis:latest
    container_name: cache
    restart: always
    tty: true
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - application

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    volumes:
       - ./docker/localstack/data:/tmp/localstack/data
       - ./docker/localstack:/localstack
       - ./docker/entrypoints/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
    environment:
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_DEFAULT_OUTPUT=$AWS_DEFAULT_OUTPUT
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - application

networks:
  application:
    external: true
